#!/usr/bin/env python3
"""
OpenFRAMP OSCAL SSP Generator — Converts parsed SSP data to OSCAL 1.1 SSP JSON.

Takes the JSON output from ssp_parser.py and generates a valid OSCAL 1.1
System Security Plan document.

Usage:
    python3 ssp_to_oscal.py <parsed-ssp.json> [--output oscal-ssp.json]
"""

import json
import sys
import uuid
from datetime import datetime, timezone


def generate_uuid():
    return str(uuid.uuid4())


def build_oscal_ssp(parsed_data, system_name="Unnamed System"):
    """Convert parsed SSP data to OSCAL 1.1 SSP format."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    
    oscal_ssp = {
        "system-security-plan": {
            "uuid": generate_uuid(),
            "metadata": {
                "title": f"System Security Plan — {system_name}",
                "last-modified": now,
                "version": "1.0.0",
                "oscal-version": "1.1.2",
                "roles": [
                    {
                        "id": "system-owner",
                        "title": "System Owner"
                    },
                    {
                        "id": "authorizing-official",
                        "title": "Authorizing Official"
                    },
                    {
                        "id": "information-system-security-officer",
                        "title": "Information System Security Officer"
                    }
                ],
                "parties": [
                    {
                        "uuid": generate_uuid(),
                        "type": "organization",
                        "name": system_name
                    }
                ]
            },
            "import-profile": {
                "href": "https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_MODERATE-baseline_profile.json"
            },
            "system-characteristics": {
                "system-ids": [
                    {
                        "id": generate_uuid(),
                        "identifier-type": "https://fedramp.gov"
                    }
                ],
                "system-name": system_name,
                "description": f"System Security Plan for {system_name}, generated by OpenFRAMP from FedRAMP SSP Appendix A.",
                "security-sensitivity-level": "moderate",
                "system-information": {
                    "information-types": [
                        {
                            "uuid": generate_uuid(),
                            "title": "System Information",
                            "description": "Information processed, stored, and transmitted by the system.",
                            "categorizations": [
                                {
                                    "system": "https://doi.org/10.6028/NIST.SP.800-60v2r1",
                                    "information-type-ids": ["C.2.8.12"]
                                }
                            ],
                            "confidentiality-impact": {"base": "fips-199-moderate"},
                            "integrity-impact": {"base": "fips-199-moderate"},
                            "availability-impact": {"base": "fips-199-moderate"}
                        }
                    ]
                },
                "security-impact-level": {
                    "security-objective-confidentiality": "fips-199-moderate",
                    "security-objective-integrity": "fips-199-moderate",
                    "security-objective-availability": "fips-199-moderate"
                },
                "status": {
                    "state": "operational"
                },
                "authorization-boundary": {
                    "description": "Authorization boundary as defined in the SSP."
                }
            },
            "system-implementation": {
                "users": [
                    {
                        "uuid": generate_uuid(),
                        "title": "System Administrator",
                        "role-ids": ["system-owner"],
                        "props": [
                            {
                                "name": "type",
                                "value": "internal"
                            }
                        ]
                    }
                ],
                "components": [
                    {
                        "uuid": generate_uuid(),
                        "type": "this-system",
                        "title": system_name,
                        "description": f"The {system_name} system as described in the SSP.",
                        "status": {
                            "state": "operational"
                        }
                    }
                ]
            },
            "control-implementation": {
                "description": f"FedRAMP Moderate baseline control implementations for {system_name}.",
                "implemented-requirements": []
            }
        }
    }
    
    # Get the this-system component UUID for references
    this_system_uuid = oscal_ssp["system-security-plan"]["system-implementation"]["components"][0]["uuid"]
    
    # Convert each control to an OSCAL implemented-requirement
    for control in parsed_data.get("controls", []):
        cid = control["control_id"]
        
        # Build the implemented-requirement
        impl_req = {
            "uuid": generate_uuid(),
            "control-id": cid.lower(),
            "description": f"Implementation of {cid}",
        }
        
        # Add responsible role as prop
        if control.get("responsible_role"):
            impl_req["props"] = [
                {
                    "name": "responsible-role",
                    "value": control["responsible_role"]
                }
            ]
        
        # Add parameters
        if control.get("parameters"):
            impl_req["set-parameters"] = []
            for param_name, param_value in control["parameters"].items():
                if param_value:
                    impl_req["set-parameters"].append({
                        "param-id": param_name.lower().replace("(", "_").replace(")", ""),
                        "values": [param_value]
                    })
        
        # Add implementation statements (parts)
        if control.get("implementation_parts"):
            impl_req["statements"] = {}
            for part_letter, narrative in control["implementation_parts"].items():
                statement_id = f"{cid.lower()}_smt.{part_letter}"
                impl_req["statements"][statement_id] = {
                    "uuid": generate_uuid(),
                    "description": narrative if narrative else f"[Implementation for {cid} part {part_letter} not yet documented]",
                    "by-components": {
                        this_system_uuid: {
                            "uuid": generate_uuid(),
                            "description": narrative if narrative else f"[Not yet documented]",
                            "implementation-status": {
                                "state": "implemented" if narrative else "planned"
                            }
                        }
                    }
                }
        
        # Add implementation status props
        status_text = control.get("implementation_status", "")
        if "Implemented" in status_text:
            if "props" not in impl_req:
                impl_req["props"] = []
            impl_req["props"].append({
                "name": "implementation-status",
                "value": "implemented"
            })
        elif "Partially" in status_text:
            if "props" not in impl_req:
                impl_req["props"] = []
            impl_req["props"].append({
                "name": "implementation-status",
                "value": "partial"
            })
        elif "Planned" in status_text:
            if "props" not in impl_req:
                impl_req["props"] = []
            impl_req["props"].append({
                "name": "implementation-status",
                "value": "planned"
            })
        
        # Add control origination
        origination = control.get("control_origination", "")
        if "Service Provider" in origination:
            if "props" not in impl_req:
                impl_req["props"] = []
            impl_req["props"].append({
                "name": "control-origination",
                "ns": "https://fedramp.gov/ns/oscal",
                "value": "sp-corporate"
            })
        
        oscal_ssp["system-security-plan"]["control-implementation"]["implemented-requirements"].append(impl_req)
    
    return oscal_ssp


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 ssp_to_oscal.py <parsed-ssp.json> [--output oscal-ssp.json]")
        print()
        print("Example:")
        print("  python3 ssp_parser.py appendix-a.docx --output parsed.json")
        print("  python3 ssp_to_oscal.py parsed.json --output oscal-ssp.json")
        sys.exit(1)
    
    input_path = sys.argv[1]
    output_path = "oscal-ssp.json"
    system_name = "FedRAMP System"
    
    if "--output" in sys.argv:
        idx = sys.argv.index("--output")
        if idx + 1 < len(sys.argv):
            output_path = sys.argv[idx + 1]
    
    if "--name" in sys.argv:
        idx = sys.argv.index("--name")
        if idx + 1 < len(sys.argv):
            system_name = sys.argv[idx + 1]
    
    # Load parsed SSP
    print(f"Loading {input_path}...")
    with open(input_path) as f:
        parsed_data = json.load(f)
    
    print(f"Found {parsed_data.get('total_controls', 0)} controls")
    
    # Generate OSCAL SSP
    print("Generating OSCAL SSP...")
    oscal_ssp = build_oscal_ssp(parsed_data, system_name)
    
    # Write output
    with open(output_path, "w") as f:
        json.dump(oscal_ssp, f, indent=2)
    
    # Summary
    impl_reqs = oscal_ssp["system-security-plan"]["control-implementation"]["implemented-requirements"]
    with_statements = sum(1 for r in impl_reqs if r.get("statements"))
    with_params = sum(1 for r in impl_reqs if r.get("set-parameters"))
    
    print()
    print("=" * 60)
    print("OSCAL SSP Generator Results")
    print("=" * 60)
    print(f"Controls converted:     {len(impl_reqs)}")
    print(f"With statements:        {with_statements}")
    print(f"With parameters:        {with_params}")
    print(f"OSCAL version:          1.1.2")
    print(f"Output:                 {output_path}")
    print("=" * 60)


if __name__ == "__main__":
    main()
