#!/usr/bin/env python3
"""
OpenFRAMP OSCAL SSP Generator — Converts parsed SSP data to OSCAL 1.1 SSP JSON.

Takes the JSON output from ssp_parser.py v2 and generates a valid OSCAL 1.1
System Security Plan document including system characteristics, contacts,
and control implementations.

Usage:
    python3 ssp_to_oscal.py <parsed-ssp.json> [--output oscal-ssp.json] [--name "System Name"]
"""

import json
import sys
import uuid
from datetime import datetime, timezone


def generate_uuid():
    return str(uuid.uuid4())


def build_oscal_ssp(parsed_data, system_name=None):
    """Convert parsed SSP data to OSCAL 1.1 SSP format."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    
    # Use system info from parser if available
    sys_info = parsed_data.get("system_information", {})
    if not system_name:
        system_name = sys_info.get("cso_name") or sys_info.get("csp_name") or "Unnamed System"
    
    service_model = sys_info.get("service_model", "")
    fips_level = sys_info.get("fips_199_level", "moderate").lower()
    if fips_level not in ["high", "moderate", "low"]:
        fips_level = "moderate"
    
    description = sys_info.get("description", f"System Security Plan for {system_name}, generated by OpenFRAMP.")
    
    # Build parties from contacts
    parties = []
    contacts = parsed_data.get("contacts", [])
    for contact in contacts:
        party = {
            "uuid": generate_uuid(),
            "type": "person",
            "name": contact.get("name", contact.get("role", "Unknown"))
        }
        
        props = []
        if contact.get("role"):
            props.append({"name": "role", "value": contact["role"]})
        if contact.get("title"):
            props.append({"name": "job-title", "value": contact["title"]})
        if contact.get("organization"):
            props.append({"name": "organization", "value": contact["organization"]})
        if props:
            party["props"] = props
        
        if contact.get("email"):
            party["email-addresses"] = [contact["email"]]
        if contact.get("phone"):
            party["telephone-numbers"] = [{"number": contact["phone"]}]
        
        parties.append(party)
    
    # Add organization party
    parties.append({
        "uuid": generate_uuid(),
        "type": "organization",
        "name": system_name
    })
    
    # Build roles
    roles = [
        {"id": "system-owner", "title": "System Owner"},
        {"id": "authorizing-official", "title": "Authorizing Official"},
        {"id": "information-system-security-officer", "title": "Information System Security Officer"}
    ]
    
    # Determine FIPS impact string
    fips_impact = f"fips-199-{fips_level}"
    
    oscal_ssp = {
        "system-security-plan": {
            "uuid": generate_uuid(),
            "metadata": {
                "title": f"System Security Plan — {system_name}",
                "last-modified": now,
                "version": "1.0.0",
                "oscal-version": "1.1.2",
                "roles": roles,
                "parties": parties,
                "props": []
            },
            "import-profile": {
                "href": f"https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_{fips_level.upper()}-baseline_profile.json"
            },
            "system-characteristics": {
                "system-ids": [
                    {
                        "id": sys_info.get("fedramp_package_id", generate_uuid()),
                        "identifier-type": "https://fedramp.gov"
                    }
                ],
                "system-name": system_name,
                "description": description if description else f"System Security Plan for {system_name}.",
                "security-sensitivity-level": fips_level,
                "system-information": {
                    "information-types": [
                        {
                            "uuid": generate_uuid(),
                            "title": "System Information",
                            "description": "Information processed, stored, and transmitted by the system.",
                            "categorizations": [
                                {
                                    "system": "https://doi.org/10.6028/NIST.SP.800-60v2r1",
                                    "information-type-ids": ["C.2.8.12"]
                                }
                            ],
                            "confidentiality-impact": {"base": fips_impact},
                            "integrity-impact": {"base": fips_impact},
                            "availability-impact": {"base": fips_impact}
                        }
                    ]
                },
                "security-impact-level": {
                    "security-objective-confidentiality": fips_impact,
                    "security-objective-integrity": fips_impact,
                    "security-objective-availability": fips_impact
                },
                "status": {
                    "state": "operational" if sys_info.get("operational_date") else "under-development"
                },
                "authorization-boundary": {
                    "description": "Authorization boundary as defined in the SSP."
                },
                "props": []
            },
            "system-implementation": {
                "users": [
                    {
                        "uuid": generate_uuid(),
                        "title": "System Administrator",
                        "role-ids": ["system-owner"],
                        "props": [{"name": "type", "value": "internal"}]
                    }
                ],
                "components": [
                    {
                        "uuid": generate_uuid(),
                        "type": "this-system",
                        "title": system_name,
                        "description": f"The {system_name} system as described in the SSP.",
                        "status": {"state": "operational"}
                    }
                ],
                "leveraged-authorizations": []
            },
            "control-implementation": {
                "description": f"FedRAMP {fips_level.capitalize()} baseline control implementations for {system_name}.",
                "implemented-requirements": []
            }
        }
    }
    
    # Add system info props
    if service_model:
        oscal_ssp["system-security-plan"]["system-characteristics"]["props"].append(
            {"name": "cloud-service-model", "value": service_model}
        )
    if sys_info.get("deployment_model"):
        oscal_ssp["system-security-plan"]["system-characteristics"]["props"].append(
            {"name": "cloud-deployment-model", "value": sys_info["deployment_model"]}
        )
    if sys_info.get("authorization_path"):
        oscal_ssp["system-security-plan"]["system-characteristics"]["props"].append(
            {"name": "authorization-type", "value": sys_info["authorization_path"]}
        )
    if sys_info.get("digital_identity_level"):
        oscal_ssp["system-security-plan"]["system-characteristics"]["props"].append(
            {"name": "identity-assurance-level", "value": sys_info["digital_identity_level"]}
        )
    
    # Clean empty props
    if not oscal_ssp["system-security-plan"]["metadata"]["props"]:
        del oscal_ssp["system-security-plan"]["metadata"]["props"]
    if not oscal_ssp["system-security-plan"]["system-characteristics"]["props"]:
        del oscal_ssp["system-security-plan"]["system-characteristics"]["props"]
    
    # Add leveraged authorizations
    for svc in parsed_data.get("leveraged_services", []):
        if svc:
            auth = {
                "uuid": generate_uuid(),
                "title": svc.get("#", svc.get("CSP/CSO Name (Name on FedRAMP", "Unknown Service")),
                "props": [{"name": k, "value": v} for k, v in svc.items() if v]
            }
            oscal_ssp["system-security-plan"]["system-implementation"]["leveraged-authorizations"].append(auth)
    
    if not oscal_ssp["system-security-plan"]["system-implementation"]["leveraged-authorizations"]:
        del oscal_ssp["system-security-plan"]["system-implementation"]["leveraged-authorizations"]
    
    # Get the this-system component UUID
    this_system_uuid = oscal_ssp["system-security-plan"]["system-implementation"]["components"][0]["uuid"]
    
    # Convert each control to an OSCAL implemented-requirement
    for control in parsed_data.get("controls", []):
        cid = control["control_id"]
        
        impl_req = {
            "uuid": generate_uuid(),
            "control-id": cid.lower(),
            "description": f"Implementation of {cid}",
        }
        
        # Add responsible role
        if control.get("responsible_role"):
            impl_req["props"] = [{"name": "responsible-role", "value": control["responsible_role"]}]
        
        # Add parameters
        if control.get("parameters"):
            impl_req["set-parameters"] = []
            for param_name, param_value in control["parameters"].items():
                if param_value:
                    impl_req["set-parameters"].append({
                        "param-id": param_name.lower().replace("(", "_").replace(")", ""),
                        "values": [param_value]
                    })
            if not impl_req["set-parameters"]:
                del impl_req["set-parameters"]
        
        # Add implementation statements
        if control.get("implementation_parts"):
            impl_req["statements"] = {}
            for part_letter, narrative in control["implementation_parts"].items():
                statement_id = f"{cid.lower()}_smt.{part_letter}"
                impl_req["statements"][statement_id] = {
                    "uuid": generate_uuid(),
                    "description": narrative if narrative else f"[Implementation for {cid} part {part_letter} not yet documented]",
                    "by-components": {
                        this_system_uuid: {
                            "uuid": generate_uuid(),
                            "description": narrative if narrative else "[Not yet documented]",
                            "implementation-status": {
                                "state": "implemented" if narrative else "planned"
                            }
                        }
                    }
                }
        
        # Add implementation status
        status_text = control.get("implementation_status", "")
        if "Implemented" in status_text:
            if "props" not in impl_req:
                impl_req["props"] = []
            impl_req["props"].append({"name": "implementation-status", "value": "implemented"})
        elif "Partially" in status_text:
            if "props" not in impl_req:
                impl_req["props"] = []
            impl_req["props"].append({"name": "implementation-status", "value": "partial"})
        elif "Planned" in status_text:
            if "props" not in impl_req:
                impl_req["props"] = []
            impl_req["props"].append({"name": "implementation-status", "value": "planned"})
        
        # Add control origination
        origination = control.get("control_origination", "")
        if "Service Provider" in origination:
            if "props" not in impl_req:
                impl_req["props"] = []
            impl_req["props"].append({
                "name": "control-origination",
                "ns": "https://fedramp.gov/ns/oscal",
                "value": "sp-corporate"
            })
        
        oscal_ssp["system-security-plan"]["control-implementation"]["implemented-requirements"].append(impl_req)
    
    return oscal_ssp


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 ssp_to_oscal.py <parsed-ssp.json> [--output oscal-ssp.json] [--name \"System Name\"]")
        print()
        print("Example:")
        print("  python3 ssp_parser.py main-ssp.docx --appendix-a appendix-a.docx --output parsed.json")
        print("  python3 ssp_to_oscal.py parsed.json --output oscal-ssp.json")
        sys.exit(1)
    
    input_path = sys.argv[1]
    output_path = "oscal-ssp.json"
    system_name = None
    
    if "--output" in sys.argv:
        idx = sys.argv.index("--output")
        if idx + 1 < len(sys.argv):
            output_path = sys.argv[idx + 1]
    
    if "--name" in sys.argv:
        idx = sys.argv.index("--name")
        if idx + 1 < len(sys.argv):
            system_name = sys.argv[idx + 1]
    
    # Load parsed SSP
    print(f"Loading {input_path}...")
    with open(input_path) as f:
        parsed_data = json.load(f)
    
    print(f"Found {parsed_data.get('total_controls', 0)} controls")
    
    # Generate OSCAL SSP
    print("Generating OSCAL SSP...")
    oscal_ssp = build_oscal_ssp(parsed_data, system_name)
    
    # Write output
    with open(output_path, "w") as f:
        json.dump(oscal_ssp, f, indent=2)
    
    # Summary
    impl_reqs = oscal_ssp["system-security-plan"]["control-implementation"]["implemented-requirements"]
    with_statements = sum(1 for r in impl_reqs if r.get("statements"))
    with_params = sum(1 for r in impl_reqs if r.get("set-parameters"))
    parties = oscal_ssp["system-security-plan"]["metadata"]["parties"]
    sys_chars = oscal_ssp["system-security-plan"]["system-characteristics"]
    
    print()
    print("=" * 60)
    print("OSCAL SSP Generator Results")
    print("=" * 60)
    print(f"System name:            {sys_chars.get('system-name', 'N/A')}")
    print(f"Security level:         {sys_chars.get('security-sensitivity-level', 'N/A')}")
    print(f"Controls converted:     {len(impl_reqs)}")
    print(f"With statements:        {with_statements}")
    print(f"With parameters:        {with_params}")
    print(f"Parties (contacts):     {len(parties)}")
    print(f"OSCAL version:          1.1.2")
    print(f"Output:                 {output_path}")
    print("=" * 60)


if __name__ == "__main__":
    main()
