services:
  openframp:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ~/.aws:/home/scanner/.aws:ro
    environment:
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
    entrypoint: ["python3", "/home/scanner/openframp/web/app.py"]